# Generated by Django 4.2.4 on 2023-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupoun', '0003_alter_offers_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
