# Generated by Django 4.2.4 on 2023-09-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variant_tv_mount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_userpurchasedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_usage', to='orders.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('order_request_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=300)),
                ('admin_approved', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('qty_updated', models.BooleanField(default=False)),
                ('payment_returned', models.BooleanField(default=False)),
                ('payment_initiated_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
        ),
    ]
