# Generated by Django 4.2.4 on 2023-09-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_damagedproducts_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagedproducts',
            name='order',
        ),
    ]
