# Generated by Django 4.2.4 on 2023-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_damagedproducts_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('order_pending', 'Order_Pending'), ('order_confirmed', 'Order_Confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('waiting_for_approval', 'Waiting for Approval'), ('returned', 'Returned')], default='order_pending', max_length=100),
        ),
    ]
