# Generated by Django 4.2.4 on 2023-09-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderdetail_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='orders.orderdetail'),
        ),
    ]
