# Generated by Django 4.2.4 on 2023-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderdetail_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='is_delivered',
            new_name='return_approved',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='return_admin_response',
            field=models.CharField(default='Return approved', max_length=300),
        ),
    ]
