# Generated by Django 4.2.4 on 2023-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_is_delivered_orderdetail_return_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='return_admin_response',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
