# Generated by Django 4.2.4 on 2023-09-08 18:06

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('rand_id', models.BigIntegerField(default=products.models.generate_random_8_digit_number, unique=True)),
                ('is_availble', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=30)),
                ('rand_id', models.BigIntegerField(default=products.models.generate_random_8_digit_number, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rand_id', models.BigIntegerField(default=products.models.generate_random_8_digit_number, unique=True)),
                ('ram', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('mr_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('screen_resolution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('no_of_usb_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_hdmi_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('tv_mount', models.CharField(blank=True, choices=[(' ', ' '), ('wall mount', 'Wall Mount'), ('table mount', 'Table Mount')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Variant_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='products.variant')),
            ],
        ),
    ]
