# Generated by Django 4.2.4 on 2023-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
