# Generated by Django 4.2.4 on 2023-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_is_availble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='tv_mount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
