# Generated by Django 4.2.4 on 2023-09-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name_alter_variant_screen_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
