# Generated by Django 4.2.4 on 2023-09-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variant_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
