# Generated by Django 4.2.4 on 2023-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
