# Generated by Django 4.2.4 on 2023-09-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_variant_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='mr_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
