# Generated by Django 4.2.4 on 2023-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_variant_mr_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant_images',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default_image.jpg', null=True, upload_to='product_images/'),
        ),
    ]
