# Generated by Django 4.2.4 on 2023-09-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variant_is_available_variant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
