# Generated by Django 4.2.4 on 2023-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
